apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spoon-dollop
  name: spoon-dollop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoon-dollop
  template:
    metadata:
      labels:
        app: spoon-dollop
        customer-db: db-mongo
        customer: rabbit-mq
    spec:
      containers:
        - image: m2iformationihab.azurecr.io/dollop
          command: ["sh"]
          args: ["-c", "yarn --dev && ./wait-for.sh spoon-rabbitmq-service.default.svc.local:5672 -- yarn dev"]
          
          name: spoon-dollop
          # volumeMounts:
          # - mountPath: ./dollop:/code
          #   name: test-volume

          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@spoon-rabbitmq-service.default.svc.local/
            - name: MONGODB_URI
              value: mongodb://spoon-mongo-service.default.svc.local:27017/spoon 
            - name: POKEMON_ROUTING_KEY
              value: pokemon
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: spoon-dollop

      # volumes:
      # - name: test-volume
      #     # livenessProbe:
      #     #   httpGet:
      #     #     path: /check
      #     #     port: 3000
      #     #   initialDelaySeconds: 2
      #     #   periodSeconds: 3