apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: de-mongo-network-policy
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            customer-db: db-mongo
      ports:
        - protocol: TCP
          port: 27017