apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: appli-redis
        image: benoitm2iregistry.azurecr.io/appli-redis
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"
        ports:
        - containerPort: 6379